/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CalendarModal: typeof import('./components/CalendarModal.vue')['default']
    ContactModal: typeof import('./components/ContactModal.vue')['default']
    CTASection: typeof import('./components/CTASection.vue')['default']
    HeroSection: typeof import('./components/HeroSection.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ServicesSection: typeof import('./components/ServicesSection.vue')['default']
    TheCounter: typeof import('./components/TheCounter.vue')['default']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
    TheInput: typeof import('./components/TheInput.vue')['default']
    TheNavigation: typeof import('./components/TheNavigation.vue')['default']
    WhyTrustSection: typeof import('./components/WhyTrustSection.vue')['default']
  }
}
